spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://182.254.208.159/Insurance_policy?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: localhost
    port: 6379
  thymeleaf:
    prefix: classpath:/templates/
server:
  servlet:
    context-path: /
logging:
  level:
    com.insurance.policy.repository: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml